time < nul

::rename existing current output graphs
perl update_current_output.pl

::execute all perl scripts to parse the logs, make data files, and plots if logs exists
if exist logs/authn.log mkdir current_output_graphs\pdweb_authn
if exist logs/authn.log (perl plot_files/pdweb.authn/authn.pl logs/authn.log) && (move authn_plot_pass.png current_output_graphs/pdweb_authn) && (move authn_plot_fail.png current_output_graphs/pdweb_authn) && (move authn_plot_pwd_exp.png current_output_graphs/pdweb_authn) && (move authn_plot_max_time.png current_output_graphs/pdweb_authn) && (move authn_plot_avg_time.png current_output_graphs/pdweb_authn) && (move authn_plot_total_time.png current_output_graphs/pdweb_authn)
if exist logs/authz.log mkdir current_output_graphs\pdweb_authz
if exist logs/authz.log (perl plot_files/pdweb.authz/authz.pl logs/authz.log) && (move authz_plot_fail.png current_output_graphs/pdweb_authz) && (move authz_plot_pass.png current_output_graphs/pdweb_authz)
if exist logs/certcallbackcache.log mkdir current_output_graphs\pdweb_certcallbackcache
if exist logs/certcallbackcache.log (perl plot_files/pdweb.certcallbackcache/certcallbackcache.pl logs/certcallbackcache.log) && (move certcallbackcache_plot_miss.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_hit.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_add.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_del.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_inactive.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_lifetime.png current_output_graphs/pdweb_certcallbackcache) && (move certcallbackcache_plot_LRU_expired.png current_output_graphs/pdweb_certcallbackcache)
if exist logs/doccache.log mkdir current_output_graphs\pdweb_doccache
if exist logs/doccache.log (perl plot_files/pdweb.doccache/doccache.pl logs/doccache.log) && (move doccache_plot_general_errors.png current_output_graphs/pdweb_doccache) && (move doccache_plot_uncachable.png current_output_graphs/pdweb_doccache) && (move doccache_plot_pending_deletes.png current_output_graphs/pdweb_doccache) && (move doccache_plot_pending_size.png current_output_graphs/pdweb_doccache) && (move doccache_plot_misses.png current_output_graphs/pdweb_doccache) && (move doccache_plot_size.png current_output_graphs/pdweb_doccache) && (move doccache_plot_count.png current_output_graphs/pdweb_doccache) && (move doccache_plot_hits.png current_output_graphs/pdweb_doccache) && (move doccache_plot_stale_hits.png current_output_graphs/pdweb_doccache) && (move doccache_plot_create_waits.png current_output_graphs/pdweb_doccache) && (move doccache_plot_cache_no_room.png current_output_graphs/pdweb_doccache) && (move doccache_plot_additions.png current_output_graphs/pdweb_doccache) && (move doccache_plot_aborts.png current_output_graphs/pdweb_doccache) && (move doccache_plot_deletes.png current_output_graphs/pdweb_doccache) && (move doccache_plot_updates.png current_output_graphs/pdweb_doccache) && (move doccache_plot_too_big_errors.png current_output_graphs/pdweb_doccache) && (move doccache_plot_MT_errors.png current_output_graphs/pdweb_doccache)
if exist logs/drains.log mkdir current_output_graphs\pdweb_drains
if exist logs/drains.log (perl plot_files/pdweb.drains/drains.pl logs/drains.log) && (move drains_plot_failed_closes.png current_output_graphs/pdweb_drains) && (move drains_plot_max_draining_FDs.png current_output_graphs/pdweb_drains) && (move drains_plot_failed_selects.png current_output_graphs/pdweb_drains) && (move drains_plot_FDs_closed_HIWAT.png current_output_graphs/pdweb_drains) && (move drains_plot_FDs_closed_FLOOD.png current_output_graphs/pdweb_drains) && (move drains_plot_timed_out_FDs.png current_output_graphs/pdweb_drains) && (move drains_plot_idle_awakenings.png current_output_graphs/pdweb_drains) && (move drains_plot_bytes_drained.png current_output_graphs/pdweb_drains) && (move drains_plot_drained_FDs.png current_output_graphs/pdweb_drains) && (move drains_plot_average_bytes_drained.png current_output_graphs/pdweb_drains)
if exist logs/http.log mkdir current_output_graphs\pdweb_http
if exist logs/http.log (perl plot_files/pdweb.http/http.pl logs/http.log) && (move http_plot_reqs.png current_output_graphs/pdweb_http) && (move http_plot_max_worker_time.png current_output_graphs/pdweb_http) && (move http_plot_max_webseal_time.png current_output_graphs/pdweb_http) && (move http_plot_total_worker_time.png current_output_graphs/pdweb_http) && (move http_plot_total_webseal_time.png current_output_graphs/pdweb_http) && (move http_plot_average_worker_time.png current_output_graphs/pdweb_http) && (move http_plot_average_webseal_time.png current_output_graphs/pdweb_http)
if exist logs/https.log mkdir current_output_graphs\pdweb_https
if exist logs/https.log (perl plot_files/pdweb.https/https.pl logs/https.log) && (move https_plot_reqs.png current_output_graphs/pdweb_https) && (move https_plot_max_worker_time.png current_output_graphs/pdweb_https) && (move https_plot_max_webseal_time.png current_output_graphs/pdweb_https) && (move https_plot_total_worker_time.png current_output_graphs/pdweb_https) && (move https_plot_total_webseal_time.png current_output_graphs/pdweb_https) && (move https_plot_average_worker_time.png current_output_graphs/pdweb_https) && (move https_plot_average_webseal_time.png current_output_graphs/pdweb_https)
if exist logs/jct_1.log perl plot_files/pdweb.jct.#/jct.pl
if exist logs/jmt.log mkdir current_output_graphs\pdweb_jmt
if exist logs/jmt.log (perl plot_files/pdweb.jmt/jmt.pl logs/jmt.log) && (move jmt_plot.png current_output_graphs/pdweb_jmt)
if exist logs/sescache.log mkdir current_output_graphs\pdweb_sescache
if exist logs/sescache.log (perl plot_files/pdweb.sescache/sescache.pl logs/sescache.log) && (move sescache_plot_miss.png current_output_graphs/pdweb_sescache) && (move sescache_plot_hit.png current_output_graphs/pdweb_sescache) && (move sescache_plot_add.png current_output_graphs/pdweb_sescache) && (move sescache_plot_del.png current_output_graphs/pdweb_sescache) && (move sescache_plot_inactive.png current_output_graphs/pdweb_sescache) && (move sescache_plot_lifetime.png current_output_graphs/pdweb_sescache) && (move sescache_plot_LRU_expired.png current_output_graphs/pdweb_sescache)
if exist logs/threads.log mkdir current_output_graphs\pdweb_threads
if exist logs/threads.log (perl plot_files/pdweb.threads/threads.pl logs/threads.log) && (move threads_plot.png current_output_graphs/pdweb_threads) && (move threads_plot_default.png current_output_graphs/pdweb_threads)
if exist logs/usersessidcache.log mkdir current_output_graphs\pdweb_usersessidcache
if exist logs/usersessidcache.log (perl plot_files/pdweb.usersessidcache/usersessidcache.pl logs/usersessidcache.log) && (move usersessidcache_plot_miss.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_add.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_del.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_hit.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_inactive.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_lifetime.png current_output_graphs/pdweb_usersessidcache) && (move usersessidcache_plot_LRU_expired.png current_output_graphs/pdweb_usersessidcache)
if exist logs/vhj_1.log perl plot_files/pdweb.vhj.#/vhj.pl

time < nul