-- DDL Statements for indexes on Table "LDAPDB2 "."LDAP_DESC"

CREATE INDEX "LDAPDB2"."LDAP_DESC_DEID" ON "LDAPDB2"."LDAP_DESC" 
		("AEID" ASC,
		 "DEID" ASC) MINPCTUSED 10 ALLOW REVERSE SCANS ;

commit;
